=== trevo-finance/trevo-traits-registry/traits/metadata_schema.json
{
    "$id": "https://trevo-finance.github.io/trevo-traits-registry/traits/metadata_schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Metadata of on-chain entity",
    "description": "Metadata of an on-chain entity, such as token, NFT, AppAgent etc.",
    "type": "object",
    "properties": {
      "metadata_id": {
        "description": "The identifier of the document with metadata. Depending on the context, this can be an identifier of on-chain entity, that metadata annotates. Or it can be an application-specific identifier.",
        "type": "string",
        "minLength": 5,
        "maxLength": 128
      },
      "title": {
        "description": "The human readable title of the document with metadata.",
        "type": "string",
        "minLength": 5,
        "maxLength": 128
      },
      "description": {
        "description": "The human readable description of the metadata document.",
        "type": "string",
        "maxLength": 1024
      },
      "traits": {
        "description": "The list of traits supported by on-chain entity, that is annotated with this metadata document.",
        "type": "object",
        "minProperties": 1,
        "propertyNames": {
          "type": "string",
          "minLength": 5,
          "maxLength": 128
        },
        "patternProperties": {
          "^.*$": { "type": "object" }
        }
      }
    },
    "required": [ "metadata_id", "title", "traits" ],
    "additionalProperties": false
}

=== trevo-finance/trevo-traits-registry/examples/nft_token.json
{
    "metadata_id": "XYZ123",
    "title": "Some title of the document",
    "description": "Some description of the document",
    "traits": {
        "named": {
            "name": "NFT token name"
        },
        "finance.trevo.wallet.square_icon": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-150.svg"
        },
        "finance.trevo.wallet.nft_token_listing_image": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-512.svg"
        },
        "finance.trevo.wallet.nft_token_cover_image": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-1920.svg"
        },
        "finance.trevo.wallet.nft_token_description": {
            "nft_token_description": "Some description of the token displayed to the user of TRAIT wallet."
        },
        "finance.trevo.wallet.nft_token_attributes": {
            "attributes": [
                {
                    "name": "Number attribute",
                    "display_type": "number",
                    "value": 123
                },
                {
                    "name": "Percentage attribute",
                    "display_type": "percentage",
                    "value": -17
                },
                {
                    "name": "String attribute",
                    "display_type": "string",
                    "value": "Some string"
                },
                {
                    "name": "Boolean attribute",
                    "display_type": "boolean",
                    "value": true
                },
                {
                    "name": "Date attribute 1",
                    "display_type": "date",
                    "value": "2018-11-13T20:20:39+00:00"
                },
                {
                    "name": "Date attribute 2",
                    "display_type": "date",
                    "value": "2018-11-13"
                },
                {
                    "name": "Date attribute 3",
                    "display_type": "date",
                    "value": "20:20:39+00:00"
                },
                {
                    "name": "Duration attribute",
                    "display_type": "duration",
                    "value": "P3D"
                }
            ]
        }
    }
}

=== trevo-finance/trevo-traits-registry/examples/nft_collection.json
{
    "metadata_id": "ABCDEFG",
    "title": "Some title of the document",
    "description": "Some description of the document",
    "traits": {
        "named": {
            "name": "NFT collection name"
        },
        "finance.trevo.wallet.square_icon": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-150.svg"
        },
        "finance.trevo.wallet.nft_collection_listing_image": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-512.svg"
        }
    }
}

=== trevo-finance/trevo-traits-registry/examples/appagent.json
{
    "metadata_id": "12345",
    "title": "Some title of the document",
    "description": "Some description of the document",
    "traits": {
        "named": {
            "name": "AppAgent name"
        },
        "finance.trevo.wallet.square_icon": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-150.svg"
        }
    }
}

=== trevo-finance/trevo-traits-registry/examples/fungible_token.json
{
    "metadata_id": "12345",
    "title": "Some title of the document",
    "description": "Some description of the document",
    "traits": {
        "named": {
            "name": "Fungible token name"
        },
        "fungible": {
            "symbol": "FUNGIBLE",
            "decimals": 12
        },
        "finance.trevo.wallet.square_icon": {
            "image_url": "https://trevo-finance.github.io/trevo-traits-registry/examples/trait-logo-150.svg"
        },
        "finance.trevo.wallet.price_feed": {
            "current_price": {
                "source": "tiingo",
                "ticker": "NVDA"
            }
        }
    }
}
